import Head from 'next/head'
import React from 'react'

const HeadSite = () => {
  return (
    <Head>
        <title>Mariane Barbosa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadSite